# Generated by Django 4.2.13 on 2026-04-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('specialite', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('permanent', 'Permanent'), ('vacataire', 'Vacataire')], max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'chef_departement'}, on_delete=django.db.models.deletion.CASCADE, related_name='jurys_geres', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_jury', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du jury',
                'verbose_name_plural': 'Membres du jury',
            },
        ),
        migrations.CreateModel(
            name='PropositionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_proposee', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel')], default='presentiel', max_length=15)),
                ('lien_visio', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise au directeur des études'), ('validee_de', 'Validée par le DE'), ('rejetee_de', 'Rejetée par le DE'), ('validee_dg', 'Validée par la DG'), ('rejetee_dg', 'Rejetée par la DG')], default='soumise', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'chef_departement'}, on_delete=django.db.models.deletion.CASCADE, related_name='propositions_jury', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_jury', to='etudiant.dossiersoutenance')),
                ('membres', models.ManyToManyField(related_name='propositions', to='chef_departement.membrejury')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidences', to='chef_departement.membrejury')),
            ],
            options={
                'verbose_name': 'Proposition de jury',
            },
        ),
    ]
