# Generated by Django 4.2.13 on 2026-04-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('auteur', models.CharField(max_length=200)),
                ('encadreur', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=20)),
                ('promotion', models.CharField(blank=True, max_length=50)),
                ('annee_academique', models.CharField(max_length=9)),
                ('entreprise_stage', models.CharField(blank=True, max_length=200)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mention', models.CharField(blank=True, max_length=20)),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_bibliotheque', to='etudiant.dossiersoutenance')),
            ],
            options={
                'verbose_name': 'Document bibliothèque',
                'ordering': ['-annee_academique', 'auteur'],
            },
        ),
    ]
