# Generated by Django 4.2.13 on 2026-04-16 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('chef', models.OneToOneField(blank=True, limit_choices_to={'role': 'chef_departement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_gere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.CreateModel(
            name='DossierSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoire_pdf', models.FileField(upload_to='memoires/%Y/%m/')),
                ('quitus_pedagogique', models.FileField(upload_to='quitus/pedagogique/%Y/')),
                ('quitus_financier', models.FileField(upload_to='quitus/financier/%Y/')),
                ('quitus_encadreur', models.FileField(upload_to='quitus/encadreur/%Y/')),
                ('memoire_final_pdf', models.FileField(blank=True, null=True, upload_to='memoires/final/%Y/')),
                ('quitus_president', models.FileField(blank=True, null=True, upload_to='quitus/president/%Y/')),
                ('taux_ia', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('analyse_ia', 'Analyse IA en cours'), ('rejete_ia', 'Rejeté — taux IA trop élevé'), ('en_instruction', 'En instruction (chef de département)'), ('valide_chef', 'Validé par le chef de département'), ('rejete_chef', 'Rejeté par le chef de département'), ('rejete_de', 'Rejeté par le DE'), ('jury_propose', 'Jury proposé'), ('valide_de', 'Validé par le directeur des études'), ('valide_dg', 'Validé par la direction générale'), ('programme', 'Soutenance programmée'), ('soutenu', 'Soutenu'), ('corrections', 'Corrections requises'), ('depot_final_soumis', 'Dépôt final soumis — en attente validation chef'), ('archive', 'Archivé')], default='soumis', max_length=30)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier de soutenance',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('promotion', models.CharField(blank=True, help_text='Ex : Promotion 2024', max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='etudiant.departement')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'unique_together': {('departement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PVSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien'), ('excellent', 'Excellent')], max_length=20)),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('admis_corrections', 'Admis avec corrections'), ('ajourne', 'Ajourné')], max_length=25)),
                ('observations', models.TextField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='etudiant.dossiersoutenance')),
                ('saisi_par', models.ForeignKey(limit_choices_to={'role': 'jury'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PV de soutenance',
            },
        ),
        migrations.CreateModel(
            name='PropositionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=400, verbose_name='Thème du mémoire / rapport')),
                ('encadreur', models.CharField(max_length=200, verbose_name="Nom de l'encadreur pédagogique")),
                ('entreprise', models.CharField(max_length=200, verbose_name="Entreprise d'accueil")),
                ('lieu_stage', models.CharField(max_length=200)),
                ('promotion', models.CharField(blank=True, max_length=50, verbose_name='Promotion')),
                ('periode_debut', models.DateField(verbose_name='Début du stage')),
                ('periode_fin', models.DateField(verbose_name='Fin du stage')),
                ('description', models.TextField(blank=True, verbose_name='Description / objectifs du stage')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='etudiant.etudiant')),
            ],
            options={
                'verbose_name': 'Proposition de thème',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammationSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soutenance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel')], default='presentiel', max_length=15)),
                ('lien_visio', models.URLField(blank=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programmation', to='etudiant.dossiersoutenance')),
            ],
            options={
                'verbose_name': 'Programmation de soutenance',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('alerte', 'Avertissement'), ('rejet', 'Rejet')], default='info', max_length=10)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='etudiant.specialite'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_etudiant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='etudiant.etudiant'),
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.propositiontheme'),
        ),
    ]
