# Generated by Django 4.2.13 on 2026-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersoutenance',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('analyse_ia', 'Analyse IA en cours'), ('rejete_ia', 'Rejeté — taux IA trop élevé'), ('en_instruction', 'En instruction (chef de département)'), ('valide_chef', 'Validé par le chef de département'), ('rejete_chef', 'Rejeté par le chef de département'), ('rejete_de', 'Rejeté par le DE'), ('jury_propose', 'Jury proposé'), ('valide_de', 'Validé par le directeur des études'), ('valide_dg', 'Validé par la direction générale'), ('programme', 'Soutenance programmée'), ('soutenu', 'Soutenu'), ('corrections', 'Corrections requises'), ('archive', 'Archivé')], default='soumis', max_length=30),
        ),
    ]
